export const SEARCH_ITEMS_START = "SEARCH_ITEMS_START";
export const SEARCH_ITEMS_SUCCESS = "SEARCH_ITEMS_SUCCESS";
export const SEARCH_ITEMS_FAILED = "SEARCH_ITEMS_FAILED";


export const SEARCH_ITEM_START = "SEARCH_ITEM_START";
export const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS";
export const SEARCH_ITEM_FAILED = "SEARCH_ITEM_FAILED";

export const SET_ITEM_KEY = "SET_ITEM_KEY";


export const REMOVE_ITEM = "REMOVE_ITEM";


export const RESET = "RESET";